# Generated by Django 4.2.3 on 2023-07-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120, verbose_name='Package description')),
            ],
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, default=0, null=True)),
                ('recordtype', models.CharField(choices=[('N', 'Normal items'), ('T', 'Titel'), ('C', 'Comment')], default='N', max_length=1)),
                ('reference', models.CharField(blank=True, max_length=20, null=True, verbose_name='Reference')),
                ('description', models.CharField(max_length=120, verbose_name='Price Item')),
                ('unit_type', models.CharField(choices=[('LS', 'Lump Sum'), ('FQ', 'Fixed Quantity'), ('EQ', 'Estimated Quantity')], default='FQ', max_length=2, verbose_name='Unit Type')),
                ('unit', models.IntegerField(choices=[(1, 'Piece'), (2, 'm'), (3, 'm²'), (4, 'hour')], default=1)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Aantal')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Unit Price')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.package')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
