# Generated by Django 4.2.3 on 2023-07-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Reference'),
        ),
    ]
