# Generated by Django 4.2.3 on 2023-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_alter_bom_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['ref']},
        ),
        migrations.RemoveField(
            model_name='bom',
            name='reference',
        ),
        migrations.AddField(
            model_name='bom',
            name='article',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='bom',
            name='ref',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Reference'),
        ),
    ]
