# Generated by Django 4.2.3 on 2023-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_alter_bom_options_remove_bom_reference_bom_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Aantal'),
        ),
    ]
