# Generated by Django 4.2.3 on 2023-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_alter_bom_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='description',
            field=models.CharField(default='', max_length=120, verbose_name='Price Item'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='ref',
            field=models.CharField(default='', max_length=20, verbose_name='Reference'),
        ),
    ]
